Update run.yml

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
     inputs:
       file_path:
-        description: 'File URL from Telegram'
+        description: 'File path in Telegram'
         required: true
       file_name:
         description: 'File name'
@@ -21,12 +21,16 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Download input file
-        run: curl -L "${{ github.event.inputs.file_path }}" -o "${{ github.event.inputs.file_name }}"
+        env:
+          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+        run: |
+          DOWNLOAD_URL="https://api.telegram.org/file/bot${TELEGRAM_BOT_TOKEN}/${{ github.event.inputs.file_path }}"
+          curl -L "$DOWNLOAD_URL" -o "${{ github.event.inputs.file_name }}"
 
       - name: Process the file
         run: |
           unzip "${{ github.event.inputs.file_name }}" -d input
-          sudo apt-get update && sudo apt-get install openjdk-17-jdk-headless zipalign
+          sudo apt-get update && sudo apt-get install openjdk-17-jdk-headless zipalign -y
           echo "Processing ${{ github.event.inputs.file_name }}..."
           java -jar redivision.jar input/framework.jar
 
@@ -34,7 +38,13 @@ jobs:
         env:
           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
         run: |
+          OUTPUT_FILE=$(find . -maxdepth 1 -name "redivision_*" | head -n 1)
+          if [ -z "$OUTPUT_FILE" ]; then
+            echo "❌ Output file not found"
+            exit 1
+          fi
+          echo "Sending: $OUTPUT_FILE"
           curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
             -F chat_id="${{ github.event.inputs.chat_id }}" \
-            -F document=@redivision_* \
+            -F document=@"$OUTPUT_FILE" \
             -F caption="✅ Dex has been redistributed"
